# Generated by Django 3.1.4 on 2020-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='films/'),
        ),
    ]
