# Generated by Django 3.1.4 on 2020-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='TvShow Title')),
                ('image', models.ImageField(upload_to='shows')),
                ('description', models.TextField(verbose_name='Show description')),
                ('date_filmed', models.DateField(verbose_name='Show Date Filmed')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Show duration')),
                ('age_limit', models.PositiveSmallIntegerField(default=3, verbose_name='Age limit')),
                ('review', models.FloatField(verbose_name='Average review')),
                ('films', models.ManyToManyField(to='films.Film')),
            ],
        ),
    ]
