# Generated by Django 3.1.4 on 2020-12-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_tvshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='duration',
            new_name='episodes_quantity',
        ),
    ]
