# Generated by Django 3.1.4 on 2020-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20201221_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anime/')),
                ('description', models.TextField(verbose_name='Anime description')),
                ('episodes_quantity', models.PositiveSmallIntegerField(verbose_name='Anime episodes')),
                ('age_limit', models.PositiveSmallIntegerField(verbose_name='Age limit of Anime')),
                ('review', models.FloatField(verbose_name='Average review')),
            ],
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='episodes_quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Show episodes'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='image',
            field=models.ImageField(upload_to='shows/'),
        ),
    ]
