# Generated by Django 3.1.4 on 2020-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20201221_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Anime title'),
        ),
    ]
