# Generated by Django 3.1.4 on 2020-12-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_anime', to='films.anime'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_shows', to='films.tvshow'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_film', to='films.film'),
        ),
    ]
