# Generated by Django 3.1.4 on 2020-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20201224_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_limit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Age limit of Anime'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(null=True, verbose_name='Anime description'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_quantity',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Anime episodes'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='review',
            field=models.FloatField(null=True, verbose_name='Average review'),
        ),
    ]
