# Generated by Django 3.1.4 on 2021-01-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20201226_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
