# Generated by Django 3.1.4 on 2021-01-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20210104_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='age_limit',
            field=models.PositiveSmallIntegerField(default=3, null=True, verbose_name='Age limit'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='date_filmed',
            field=models.DateField(null=True, verbose_name='Show Date Filmed'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(null=True, verbose_name='Show description'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='episodes_quantity',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Show episodes'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='review',
            field=models.FloatField(null=True, verbose_name='Average review'),
        ),
    ]
