# Generated by Django 3.1.4 on 2021-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210106_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_limit',
            field=models.PositiveSmallIntegerField(default=3, null=True, verbose_name='Age limit'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_filmed',
            field=models.DateField(null=True, verbose_name='Date Filmed'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(null=True, verbose_name='Film description'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Film duration'),
        ),
        migrations.AlterField(
            model_name='film',
            name='review',
            field=models.FloatField(null=True, verbose_name='Average review'),
        ),
    ]
