# Generated by Django 3.1.4 on 2021-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20210108_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
