# Generated by Django 3.1.4 on 2021-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20210108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Film Title'),
        ),
    ]
