# Generated by Django 3.1.4 on 2021-01-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_auto_20210113_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_anime', to='films.anime')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_film', to='films.film')),
                ('shows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_shows', to='films.tvshow')),
            ],
        ),
    ]
