# Generated by Django 3.1.4 on 2021-01-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
