# Generated by Django 3.1.4 on 2020-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_anime_title'),
        ('cast', '0002_cast_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Character name')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other...')], max_length=40)),
                ('image', models.ImageField(upload_to='Character/')),
                ('anime', models.ManyToManyField(to='films.Anime')),
            ],
        ),
    ]
