# Generated by Django 3.1.4 on 2020-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_tvshow_films'),
        ('cast', '0003_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Actor's name")),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('bisexual', 'Bisexual'), ('other', 'Other...')], max_length=40)),
                ('image', models.ImageField(null=True, upload_to='tvactor/')),
                ('films', models.ManyToManyField(to='films.TvShow')),
            ],
        ),
    ]
