# Generated by Django 3.1.4 on 2020-12-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_comment'),
        ('cast', '0005_auto_20201221_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='films',
            field=models.ManyToManyField(related_name='casts', to='films.Film'),
        ),
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ManyToManyField(related_name='characters', to='films.Anime'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other...')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tvactor',
            name='films',
            field=models.ManyToManyField(related_name='tvactors', to='films.TvShow'),
        ),
    ]
